export const CATEGORY_LABELS: Record<string, string> = {
  DEMOGRAFIA: "Demografia",
  ECONOMIA: "Economia",
  EMPREGO_RENDA: "Emprego e renda",
  SAUDE: "Saúde",
  EDUCACAO: "Educação",
  SEGURANCA: "Segurança",
  MEIO_AMBIENTE: "Meio ambiente",
  INFRAESTRUTURA: "Infraestrutura",
  CONTAS_PUBLICAS: "Contas públicas",
  HABITACAO: "Habitação",
  SANEAMENTO: "Saneamento",
  AGRICULTURA: "Agricultura",
  INDUSTRIA: "Indústria",
  ASSISTENCIA_SOCIAL: "Assistência social",
  MULHERES: "Mulheres",
  CRIANCAS: "Crianças",
  IDOSOS: "Idosos",
  DESENVOLVIMENTO_REGIONAL: "Desenvolvimento regional",
  JUSTICA: "Justiça",
  GESTAO_PUBLICA: "Gestão pública",
  COMERCIO_EXTERIOR: "Comércio exterior",
  TRANSPARENCIA_CONTROLE: "Transparência e controle",
};

export const CATEGORY_ORDER = Object.keys(CATEGORY_LABELS);
